puts "\nThe Truth Tables"

puts "\n"

puts "NOT\t\t true?"
puts "------------------------"
puts "!false\t\t true"
puts "!true\t\t false"
puts "\n"

puts "OR (||)\t\t true?"
puts "------------------------"
puts "true || false\t true"
puts "true || true\t true"
puts "false || true\t true"
puts "false || false\t false"
puts "\n"

puts "AND (&&)\t true?"
puts "------------------------"
puts "true && false\t false"
puts "true && true\t true"
puts "false && true\t false"
puts "false && false\t false"
puts "\n"

puts "NOT OR\t\t\t true?"
puts "-------------------------------"
puts "not (true || false)\t false"
puts "not (true || true)\t false"
puts "not (false || true)\t false"
puts "not (false || false)\t true"
puts "\n"

puts "NOT AND\t\t\t true?"
puts "-------------------------------"
puts "!(true && false)\t true"
puts "!(true && true)\t\t false"
puts "!(false && true)\t true"
puts "!(false && false)\t true"
puts "\n"

puts "!=\t\t true?"
puts "------------------------"
puts "1 != 0\t\t true"
puts "1 != 1\t\t false"
puts "0 != 1\t\t true"
puts "0 != 0\t\t false"
puts "\n"

puts "==\t\t true?"
puts "------------------------"
puts "1 == 0\t\t false"
puts "1 == 1\t\t true"
puts "0 == 1\t\t false"
puts "0 == 0\t\t true"
puts "\n"
